name: Build CSharpClient

on:
  push:
    branches: [ master, 800x600 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install WebSocket-Sharp 1.0.3rc11
        run: dotnet add package WebSocketSharp --version 1.0.3-rc11
      
      - name: Use MSBuild to compile debug version
        run: msbuild
        
      - name: Upload Artifact - Debug Binary
        uses: 'actions/upload-artifact@v2'
        with:
          name: Binary-debug
          path: './bin/Debug/*.exe'

      - name: Use MSBuild to compile release version
        run: msbuild -property:Configuration=Release
        
      - name: Upload Artifact - Release Binary
        uses: 'actions/upload-artifact@v2'
        with:
          name: Binary-release
          path: './bin/Release/*.exe'
