# This is a basic workflow to help you get started with Actions

name: Build CSharpClient

on:
  push:
    branches: [ master, 800x600 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Use MSBuild to compile debug version
        run: msbuild -verbosity:diag
        
      - name: Upload Artifact - Debug Binary
        uses: 'actions/upload-artifact@v2'
        with:
          name: Binary-debug
          path: './bin/*.exe'

      - name: Use MSBuild to compile release version
        run: msbuild -verbosity:diag -property:Configuration=Release
        
      - name: Upload Artifact - Release Binary
        uses: 'actions/upload-artifact@v2'
        with:
          name: Binary-release
          path: './bin/*.exe'
